'use strict';
const $=id=>document.getElementById(id);
const state={files:[null,null,null],regVerified:false,regNeedsConfirmation:false,vinConfirmed:false,mileageConfirmed:false,mot:null,gps:null,token:null,duplicate:false,allowAttempt:false};
const normReg=s=>(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const normVin=s=>(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/[IOQ]/g,'');
const escDrive=s=>String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'");
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const setStatus=(id,text,type='waiting')=>{const el=$(id);el.textContent=text;el.className='status '+type};

function settings(){return{backend:localStorage.backend||'',clientId:localStorage.googleClientId||''}}
function maskSetting(value,kind){if(!value)return'Not saved';if(kind==='url'){try{const u=new URL(value);return `${u.protocol}//${u.hostname.slice(0,5)}••••${u.hostname.slice(-8)}`}catch{return'Saved'}}return value.length>18?`${value.slice(0,6)}••••${value.slice(-12)}`:'Saved'}
function renderSettingsSummary(){const s=settings();$('settingsSummary').textContent=`Backend: ${maskSetting(s.backend,'url')} · Google Client ID: ${maskSetting(s.clientId,'id')}`;$('settingsSummary').className='small '+(s.backend&&s.clientId?'ok':'waiting')}
function validVin(){return /^[A-HJ-NPR-Z0-9]{17}$/.test($('vin').value)}
function validMileage(){return /^\d{1,8}$/.test($('mileage').value)&&Number($('mileage').value)>=0}
function resetAfterFieldChange(kind){if(kind==='reg'){state.regVerified=false;state.mot=null;setStatus('motStatus','MOT history must be checked again')}if(kind==='vin')state.vinConfirmed=false;if(kind==='mileage')state.mileageConfirmed=false;renderReady()}
function renderReady(){
 const checks=[['Registration verified',state.regVerified],['VIN confirmed',state.vinConfirmed&&validVin()],['Mileage confirmed',state.mileageConfirmed&&validMileage()],['MOT history checked',!!state.mot],['Three photos captured',state.files.every(Boolean)],['GPS captured',!!state.gps],['Google Drive connected',!!state.token]];
 const pending=checks.filter(x=>!x[1]).map(x=>x[0]); const ready=!pending.length&&!state.duplicate;
 $('ready').innerHTML=(ready?'Ready to Upload':'Not ready to upload')+'<ul class="checks">'+checks.map(([n,v])=>`<li>${v?'✓':'○'} ${n}</li>`).join('')+'</ul>'+(state.duplicate?'<div>Existing vehicle folder found — choose a new attempt.</div>':'');
 $('ready').className='card status ready '+(ready?'ok':'waiting'); $('upload').disabled=!ready; return ready;
}
function requestGps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not supported on this device.'));navigator.geolocation.getCurrentPosition(p=>{state.gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMetres:p.coords.accuracy,capturedAt:new Date().toISOString()};setStatus('gpsStatus',`Captured at inspection start · accuracy ±${Math.round(p.coords.accuracy)} m`,'ok');renderReady();resolve(state.gps)},reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0})})}
async function beginInspection(){setStatus('initialGpsStatus','Requesting precise location…','waiting');$('beginInspection').disabled=true;try{await requestGps();setStatus('initialGpsStatus','Location approved and captured. Inspection unlocked.','ok');setTimeout(()=>$('gpsGate').classList.add('hidden'),350)}catch(e){setStatus('initialGpsStatus',`Location is required: ${e.message} Enable access in iPhone Settings, then try again.`,'bad');$('beginInspection').disabled=false}}

async function runOcr(file,kind){
 if(!window.Tesseract)throw new Error('OCR library is not available. Check the internet connection and retry.');
 const id='ocr'+kind; $(id).textContent='Reading photo locally…';
 const result=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')$(id).textContent=`Reading photo locally… ${Math.round((m.progress||0)*100)}%`}});
 $(id).textContent='OCR complete'; return{text:result.data.text||'',confidence:Number(result.data.confidence)||0};
}
const confusion={O:'0',Q:'0',D:'0',I:'1',L:'1',Z:'2',S:'5',G:'6',B:'8'};
const shape=s=>[...s].map(c=>confusion[c]||c).join('');
function registrationCandidates(text){return (text.toUpperCase().match(/[A-Z0-9]{2,9}/g)||[]).map(normReg)}
function classifyReg(entered,text,confidence){
 const candidates=registrationCandidates(text); if(candidates.includes(entered))return{type:confidence>=60?'exact':'likely',read:entered,confidence};
 let likely=candidates.find(c=>c.length===entered.length&&shape(c)===shape(entered));
 if(!likely)likely=candidates.find(c=>{if(Math.abs(c.length-entered.length)>1)return false;let d=Array.from({length:c.length+1},(_,i)=>i);for(let i=1;i<=entered.length;i++){let n=[i];for(let j=1;j<=c.length;j++)n[j]=Math.min(n[j-1]+1,d[j]+1,d[j-1]+(shape(entered[i-1])===shape(c[j-1])?0:1));d=n}return d[c.length]===1});
 return likely?{type:'likely',read:likely}:{type:'fail',read:candidates.sort((a,b)=>Math.abs(a.length-entered.length)-Math.abs(b.length-entered.length))[0]||'No plate text found'};
}
function extractVin(text){const runs=(text.toUpperCase().match(/[A-Z0-9\s-]{17,25}/g)||[]).map(normVin).filter(v=>v.length>=17);return runs.map(v=>v.slice(0,17)).find(v=>/^[A-HJ-NPR-Z0-9]{17}$/.test(v))||''}
function extractMileage(text){const nums=(text.match(/\d[\d ,.]{2,8}/g)||[]).map(x=>x.replace(/\D/g,'')).filter(x=>x.length>=3&&x.length<=8).map(Number).filter(n=>n<=99999999);return nums.length?String(nums.sort((a,b)=>a-b)[0]):''}

async function photoChanged(n){
 const file=$('photo'+n).files[0];state.files[n-1]=file||null;if(!file)return renderReady();$('preview'+n).src=URL.createObjectURL(file);
 try{const ocr=await runOcr(file,n);const text=ocr.text;if(n===1){state.regVerified=false;state.regNeedsConfirmation=false;$('confirmReg').classList.add('hidden');const entered=normReg($('registration').value);if(!entered){setStatus('regCompare','Enter the registration, then retake Photo 1','bad')}else{const r=classifyReg(entered,text,ocr.confidence);setStatus('regCompare',`Entered: ${entered} · OCR read: ${r.read} · Confidence: ${Math.round(ocr.confidence)}%`+(r.type==='exact'?' · Exact high-confidence match':r.type==='likely'?' · Likely/low-confidence reading — tester confirmation required':' · No acceptable match — retake Photo 1'),r.type==='exact'?'ok':r.type==='likely'?'waiting':'bad');if(r.type==='exact')state.regVerified=true;if(r.type==='likely'){state.regNeedsConfirmation=true;$('confirmReg').classList.remove('hidden')}}}if(n===2){const v=extractVin(text);if(v)$('vin').value=v;state.vinConfirmed=false;setStatus('vinStatus',v?'Candidate VIN found — tester confirmation required':'No valid VIN found — enter it manually','waiting')}if(n===3){const m=extractMileage(text);if(m)$('mileage').value=m;state.mileageConfirmed=false;setStatus('mileageStatus',m?`Candidate ${Number(m).toLocaleString()} miles — tester confirmation required`:'No likely mileage found — enter it manually','waiting')}}catch(e){$('ocr'+n).textContent=e.message;setStatus(n===1?'regCompare':n===2?'vinStatus':'mileageStatus','OCR could not complete; retake or enter manually','bad')}renderReady();
}

async function api(path,options={}){const base=settings().backend.replace(/\/$/,'');if(!base)throw new Error('Enter the secure backend URL first.');const r=await fetch(base+path,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||`Request failed (${r.status})`);return data}
function vehicleRecord(data){return Array.isArray(data)?data[0]:data.vehicle||data}
async function checkMot(){try{const reg=normReg($('registration').value);if(!reg)throw new Error('Enter a registration first.');setStatus('motStatus','Checking DVSA MOT history…');const data=await api('/mot/registration/'+encodeURIComponent(reg));const vehicle=vehicleRecord(data);const tests=vehicle?.motTests||vehicle?.motTest||[];const latest=[...tests].sort((a,b)=>new Date(b.completedDate||b.testDate)-new Date(a.completedDate||a.testDate))[0]||null;state.mot={checkedAt:new Date().toISOString(),registration:reg,latest,raw:vehicle};setStatus('motStatus',latest?`Latest MOT: ${latest.testResult||latest.result||'record found'} · ${latest.completedDate||latest.testDate||'date unavailable'} · ${latest.odometerValue||latest.odometer?.value||'—'} ${latest.odometerUnit||latest.odometer?.unit||''}`:'DVSA check complete — no MOT test record returned','ok');renderReady()}catch(e){state.mot=null;setStatus('motStatus',e.message,'bad');renderReady()}}

function driveHeaders(json=true){return{Authorization:'Bearer '+state.token,...(json?{'Content-Type':'application/json'}:{})}}
async function driveJson(url,options={}){const r=await fetch(url,{...options,headers:{...driveHeaders(options.body!==undefined),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||`Google Drive error (${r.status})`);return d}
async function findFolder(name,parent){const q=["mimeType='application/vnd.google-apps.folder'","trashed=false",`name='${escDrive(name)}'`,parent&&`'${parent}' in parents`].filter(Boolean).join(' and ');const d=await driveJson('https://www.googleapis.com/drive/v3/files?spaces=drive&fields=files(id,name)&q='+encodeURIComponent(q),{method:'GET',body:undefined});return d.files?.[0]||null}
async function ensureFolder(name,parent){return(await findFolder(name,parent))||driveJson('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:parent?[parent]:undefined})})}
async function existingVehicleFolders(dateId,reg){const q=`mimeType='application/vnd.google-apps.folder' and trashed=false and '${dateId}' in parents`;const d=await driveJson('https://www.googleapis.com/drive/v3/files?spaces=drive&fields=files(id,name)&q='+encodeURIComponent(q),{method:'GET',body:undefined});return(d.files||[]).filter(f=>f.name===reg||f.name.startsWith(reg+' - '))}
async function uploadFile(name,blob,parent,mime=blob.type||'application/octet-stream'){const boundary='mot_'+crypto.randomUUID();const meta=JSON.stringify({name,parents:[parent]});const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`,blob,`\r\n--${boundary}--`]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name',{method:'POST',headers:{Authorization:'Bearer '+state.token,'Content-Type':'multipart/related; boundary='+boundary},body});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||'Drive upload failed');return d}
async function getDateFolder(){const root=await ensureFolder('MOT Evidence');return ensureFolder(today(),root.id)}
async function upload(){if(!renderReady())return;try{$('upload').disabled=true;$('uploadStatus').textContent='Checking for an existing folder…';$('progress').value=0;const dateFolder=await getDateFolder();const reg=normReg($('registration').value);const duplicates=await existingVehicleFolders(dateFolder.id,reg);if(duplicates.length&&!state.allowAttempt){state.duplicate=true;setStatus('duplicateStatus',`A folder for ${reg} already exists today. Upload stopped.`,'bad');$('newAttempt').classList.remove('hidden');return renderReady()}const base=`${reg} - ${Number($('mileage').value)}mi`;let folderName=base;if(state.allowAttempt){let attempt=2;while(await findFolder(`${base} - Attempt ${attempt}`,dateFolder.id))attempt++;folderName=`${base} - Attempt ${attempt}`}else if(await findFolder(base,dateFolder.id)){state.duplicate=true;setStatus('duplicateStatus',`Folder ${base} already exists. Upload stopped.`,'bad');$('newAttempt').classList.remove('hidden');return renderReady()}const vehicle=await ensureFolder(folderName,dateFolder.id);setStatus('duplicateStatus','No duplicate conflict — uploading','ok');const names=['01-Vehicle.jpg','02-VIN.jpg','03-Mileage.jpg'];for(let i=0;i<3;i++){$('uploadStatus').textContent=`Uploading ${i+1} of 4…`;await uploadFile(names[i],state.files[i],vehicle.id);$('progress').value=i+1}const summary={schemaVersion:2,registration:reg,vin:$('vin').value,mileage:Number($('mileage').value),capturedAt:new Date().toISOString(),driveFolder:folderName,attempt:state.allowAttempt,gps:state.gps,registrationVerification:{confirmed:true,method:state.regNeedsConfirmation?'ocr-likely-tester-confirmed':'ocr-exact'},vinConfirmation:{confirmed:true,validFormat:true},mileageConfirmation:{confirmed:true},motHistory:state.mot,uploads:names};await uploadFile('04-Evidence-Summary.json',new Blob([JSON.stringify(summary,null,2)],{type:'application/json'}),vehicle.id,'application/json');$('progress').value=4;$('uploadStatus').textContent=`Upload complete: ${folderName}. Local photos have now been cleared.`;for(let i=1;i<=3;i++){$('photo'+i).value='';$('preview'+i).removeAttribute('src')}state.files=[null,null,null];state.allowAttempt=false;state.duplicate=false;renderReady()}catch(e){$('uploadStatus').textContent=`Upload stopped: ${e.message}. Local photos were kept for retry.`;renderReady()}}

function connectDrive(){const id=settings().clientId;if(!id)return setStatus('connectionStatus','Enter and save the Google OAuth Client ID first.','bad');if(!google?.accounts?.oauth2)return setStatus('connectionStatus','Google sign-in is still loading. Try again.','bad');google.accounts.oauth2.initTokenClient({client_id:id,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(r.error)return setStatus('connectionStatus',r.error,'bad');state.token=r.access_token;setStatus('connectionStatus','Google Drive connected for this session.','ok');renderReady()}}).requestAccessToken({prompt:''})}

addEventListener('DOMContentLoaded',()=>{$('backend').value=settings().backend;$('clientId').value=settings().clientId;$('saveSettings').onclick=()=>{localStorage.backend=$('backend').value.trim().replace(/\/$/,'');localStorage.googleClientId=$('clientId').value.trim();$('connectionStatus').textContent='Settings saved on this device.'};$('connectDrive').onclick=connectDrive;$('checkMot').onclick=checkMot;[1,2,3].forEach(n=>$('photo'+n).onchange=()=>photoChanged(n));$('registration').oninput=()=>resetAfterFieldChange('reg');$('vin').oninput=()=>resetAfterFieldChange('vin');$('mileage').oninput=()=>resetAfterFieldChange('mileage');$('confirmReg').onclick=()=>{if(state.regNeedsConfirmation){state.regVerified=true;$('confirmReg').classList.add('hidden');setStatus('regCompare',`Entered: ${normReg($('registration').value)} · Likely OCR reading confirmed by tester`,'ok');renderReady()}};$('confirmVin').onclick=async()=>{const v=normVin($('vin').value);$('vin').value=v;if(!validVin())return setStatus('vinStatus','VIN must be exactly 17 characters and cannot contain I, O or Q.','bad');try{const d=await api('/mot/vin/'+encodeURIComponent(v));const r=normReg(vehicleRecord(d)?.registration||vehicleRecord(d)?.registrationNumber);if(r&&r!==normReg($('registration').value))throw new Error(`DVSA VIN lookup returned ${r}, not ${normReg($('registration').value)}.`);state.vinConfirmed=true;setStatus('vinStatus','VIN format valid, DVSA match checked, and tester confirmed.','ok')}catch(e){state.vinConfirmed=false;setStatus('vinStatus',e.message,'bad')}renderReady()};$('confirmMileage').onclick=()=>{if(!validMileage())return setStatus('mileageStatus','Enter digits only.','bad');state.mileageConfirmed=true;const latest=state.mot?.latest;const old=Number(String(latest?.odometerValue||latest?.odometer?.value||'').replace(/\D/g,''));setStatus('mileageStatus',old&&Number($('mileage').value)<old?`Confirmed, but lower than latest MOT mileage (${old.toLocaleString()}). Review before upload.`:`Confirmed: ${Number($('mileage').value).toLocaleString()} miles`,old&&Number($('mileage').value)<old?'waiting':'ok');renderReady()};$('captureGps').onclick=()=>navigator.geolocation.getCurrentPosition(p=>{state.gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMetres:p.coords.accuracy,capturedAt:new Date().toISOString()};setStatus('gpsStatus',`Captured · accuracy ±${Math.round(p.coords.accuracy)} m`,'ok');renderReady()},e=>setStatus('gpsStatus',e.message,'bad'),{enableHighAccuracy:true,timeout:15000});$('newAttempt').onclick=()=>{state.allowAttempt=true;state.duplicate=false;$('newAttempt').classList.add('hidden');setStatus('duplicateStatus','New attempt explicitly selected. A numbered attempt folder will be created.','waiting');renderReady()};$('upload').onclick=upload;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderReady()});

addEventListener('DOMContentLoaded',()=>{
 renderSettingsSummary();
 $('settingsPanel').open=!(settings().backend&&settings().clientId);
 $('saveSettings').onclick=()=>{localStorage.backend=$('backend').value.trim().replace(/\/$/,'');localStorage.googleClientId=$('clientId').value.trim();renderSettingsSummary();$('settingsPanel').open=false;$('connectionStatus').textContent='Settings saved privately on this device.'};
 $('beginInspection').onclick=beginInspection;
 $('captureGps').onclick=async()=>{try{await requestGps()}catch(e){setStatus('gpsStatus',`Location is required: ${e.message}`,'bad')}};
 new MutationObserver(()=>{if($('uploadStatus').textContent.startsWith('Upload complete:'))setTimeout(()=>{state.gps=null;setStatus('gpsStatus','A fresh location is required for the next inspection','waiting');setStatus('initialGpsStatus','Waiting for location approval for the next inspection','waiting');$('beginInspection').disabled=false;$('gpsGate').classList.remove('hidden');renderReady()},600)}).observe($('uploadStatus'),{childList:true});
});
